### ISSUE TITLE
Failling to install

### ISSUE THREAD

**Issue by NothinRandom** [corelight/zeek-community-id#9] opened 2020-04-19 20:56 UTC
zeek 3.1.2
cmake 3.15.7

`zkg install --force zeek/corelight/zeek-community-id` is throwing installation error:

```
Failed installing "zeek/corelight/zeek-community-id": package build_command failed, see log in /root/.zkg/logs/zeek-community-id-build.log
error: incomplete installation, the follow packages failed to be installed: zeek/corelight/zeek-community-id (1.2)
```

However, no log file exists.  I [forked the bro](https://github.com/NothinRandom/bro-community-id) one a few months ago to convert over to zeek 3.x; this one installs and works fine except for failing some tests.  It's strange because other packages are installing just fine with zkg except for this one.

looking at meta file, could it be the new `cd build` that's causing the issue?
https://github.com/corelight/zeek-community-id/blob/master/zkg.meta#L4

**Comment by 0snap** [comment] 2020-04-24 08:29
This appears to be the same issue as [issue 6](https://github.com/corelight/zeek-community-id/issues/6). It just has not been fixed by that PR. I can still reproduce this, alas, it's still not possible to install the plugin on Zeek 3.1.2 and the logs do not show anything.

**Comment by NothinRandom** [comment] 2020-04-27 20:16
> This appears to be the same issue as [issue 6](https://github.com/corelight/zeek-community-id/issues/6). It just has not been fixed by that PR. I can still reproduce this, alas, it's still not possible to install the plugin on Zeek 3.1.2 and the logs do not show anything.

I could be wrong, but I don't think it installs at all for any Zeek 3.x.

**Comment by 0snap** [comment] 2020-04-28 07:19
@ckreibich any updates on this?

**Comment by ckreibich** [comment] 2020-04-30 17:34
I see the package installing fine on 3.1.1 over here, and failing on 3.2 because of incompatibilities in Zeek that cause compilation to fail. I'll need to look at 3.1.2 to see if I can reproduce. It'd be disheartening if a minor version change can have this effect.

A higher-level point: It's becoming very clear that we'll need CI to test the build across multiple Zeek versions. This shouldn't be a package-by-package setup, but something to consider more broadly, to be discussed with the open-source project.

**Comment by ckreibich** [comment] 2020-04-30 19:11
Mhmm. The package installs fine for me with 3.1.2:
```
$ zeek --version
zeek version 3.1.2
```
In a local clone of the package:

```
$ zkg install .
The following packages will be INSTALLED:
  /home/christian/t1/zeek-community-id (master)

Proceed? [Y/n]
Running unit tests for "/home/christian/t1/zeek-community-id"
Installing "/home/christian/t1/zeek-community-id"...
Installed "/home/christian/t1/zeek-community-id" (master)
Loaded "/home/christian/t1/zeek-community-id"
```
```
$ zeek -N | grep Community
Corelight::CommunityID - "Community ID" flow hash support in the connection log (dynamic, version 1.1.0)
```

**Comment by NothinRandom** [comment] 2020-04-30 22:47
@ckreibich, could you try this on a new host/VM?  I've tried to install package with different Zeek 3.x, but same issue.

**Comment by ckreibich** [comment] 2020-05-02 00:15
Actually, let me propose something different, @NothinRandom. All that `zkg` does is follow the `build_command` instruction in zkg.meta, which is `./configure && cd build && make`. Could you please try these on a fresh clone of the Community ID repo and share the results? My hunch is you're hitting something very basic.

**Comment by 0snap** [comment] 2020-05-04 10:12
@ckreibich I created the following, minimal Dockerfile to test installation:

```
FROM debian:buster

RUN apt-get update -qqy && apt-get install -qqy python3-dev build-essential \
  cmake swig git-core flex bison libssl-dev zlib1g-dev libpcap-dev python3-pip

WORKDIR /opt/zeek

RUN git clone https://github.com/zeek/zeek .
RUN git checkout v3.1.2 && \
  git fetch && \
  git submodule update --recursive --init

RUN ./configure --prefix=/opt/zeek --with-python=/usr/bin/python3 --build-type=Release
RUN make -j4
RUN make install

## Install plugin
RUN pip3 install --upgrade pip && pip3 install zkg
RUN PATH=/opt/zeek/bin:$PATH zkg autoconfig && cat /root/.zkg/config
# RUN PATH=/opt/zeek/bin:$PATH zkg install --force corelight/zeek-community-id

CMD bash
```

Download it somewhere. Then you can build it with `docker build -f Dockerfile_corelight . -t zeek-test`.

When you uncomment the line with the plugin installation, the build fails. To retry and inspect the installation, first build it without the plugin install, then exec into the container and try again:
```
docker run -ti zeek-test bash
PATH=/opt/zeek/bin:$PATH zkg install --force corelight/zeek-community-id
cat /root/.zkg/logs/zeek-community-id-build.log
```

**Comment by ckreibich** [comment] 2020-05-04 19:01
Thanks @0ortmann, very helpful. It turns out that the failure isn't really about the current Community ID codebase: when you use zkg to install from the official package source, it still pulls down version 1.2, i.e., the old one. I just pushed a 1.3 tag and official version bump and will look into getting this resolved.

In the meantime if you want to install the package, do one of the following:
- `zkg install --version 1.3 corelight/zeek-community-id`
- clone the package, cd into it, run `zkg install .`

**Comment by NothinRandom** [comment] 2020-05-04 20:00
@ckreibich, I tried building inside my docker and outside of it, and new update works.  I didn't need to specify version, and this worked fine `RUN zkg install --force zeek/corelight/zeek-community-id`.  @0ortmann, objections to closing this issue?

**Comment by 0snap** [comment] 2020-05-05 07:25
Thanks for the clarification, the new version works :+1: 
@NothinRandom no objections to closing this.

**Comment by ckreibich** [comment] 2020-05-05 16:28
Thanks all, closing issue.

**Closed as completed by ckreibich** 2020-05-05 16:28 UTC
